# Declare global variables for R CMD check
utils::globalVariables(
  c("Date", "Storage", "Month", "Release")
)

#' Compute daily reservoir releases from a storage rule
#'
#' Computes daily reservoir releases using storage, seasonal inflow weights,
#' and either a linear or logistic storage-to-release relationship.
#'
#' This function is reservoir-independent. The user must provide the
#' appropriate minimum and maximum storage and release values for the
#' reservoir being modeled.
#'
#' @param df Data frame containing daily reservoir data. It must contain:
#'   \describe{
#'     \item{Date}{Date values.}
#'     \item{Storage}{Storage in million cubic metres (MCM).}
#'   }
#' @param seasonal_weights Named numeric vector of 12 monthly seasonal
#'   weights. The names must be `month.abb`, such as `"Jan"`, `"Feb"`, and
#'   `"Mar"`.
#' @param Smin Minimum operational storage in MCM.
#' @param Smax Maximum operational storage in MCM.
#' @param Qmin Minimum release in cubic metres per second.
#' @param Qmax Maximum release in cubic metres per second.
#' @param rule Storage-to-release relationship. Either `"linear"` or
#'   `"logistic"`.
#' @param logistic_k Steepness parameter for the logistic rule. Larger values
#'   produce a sharper transition.
#' @param logistic_midpoint Storage index at which the logistic release
#'   fraction equals 0.5. Must be between 0 and 1.
#' @param normalize_weights Logical. If TRUE, seasonal weights are divided by
#'   their mean so that their average is approximately 1.
#' @param missing_weight Value used for a month whose seasonal weight is
#'   missing. The default is 1, meaning no seasonal adjustment.
#' @param cap_release Logical. If TRUE, releases are constrained between
#'   `Qmin` and `Qmax` after seasonal adjustment. If FALSE, seasonal weights
#'   may cause releases to exceed `Qmax` or fall below `Qmin`.
#' @param plot Logical. If TRUE, generates a daily release plot when
#'   `ggplot2` is installed.
#'
#' @return A data frame with columns:
#'   \describe{
#'     \item{Date}{Date of the record.}
#'     \item{Storage}{Storage in MCM.}
#'     \item{Month}{Three-letter month abbreviation.}
#'     \item{Storage_Index}{Storage normalized between 0 and 1.}
#'     \item{Seasonal_Weight}{Seasonal inflow weight used.}
#'     \item{Release_Fraction}{Release fraction generated by the selected
#'       storage rule.}
#'     \item{Release}{Final release in cubic metres per second.}
#'   }
#'
#' @details
#' Storage is first normalized as:
#'
#' \deqn{
#' Storage\_Index =
#' \frac{Storage - Smin}{Smax - Smin}
#' }
#'
#' The storage index is constrained between 0 and 1.
#'
#' For the linear rule:
#'
#' \deqn{
#' Release\_Fraction = Storage\_Index
#' }
#'
#' For the logistic rule:
#'
#' \deqn{
#' Release\_Fraction =
#' \frac{1}{1 + exp[-k(Storage\_Index - midpoint)]}
#' }
#'
#' The unadjusted release is calculated as:
#'
#' \deqn{
#' Q = Qmin + Release\_Fraction(Qmax - Qmin)
#' }
#'
#' The seasonal adjustment is then applied:
#'
#' \deqn{
#' Release = Q \times Seasonal\_Weight
#' }
#'
#' @export
wad_release_policy <- function(
    df,
    seasonal_weights,
    Smin,
    Smax,
    Qmin,
    Qmax,
    rule = c("linear", "logistic"),
    logistic_k = 8,
    logistic_midpoint = 0.55,
    normalize_weights = TRUE,
    missing_weight = 1,
    cap_release = FALSE,
    plot = FALSE
) {
  ## ---- Match arguments ----
  rule <- match.arg(rule)

  ## ---- Validate data frame ----
  if (!is.data.frame(df)) {
    stop("df must be a data frame.")
  }

  required_cols <- c("Date", "Storage")

  if (!all(required_cols %in% names(df))) {
    stop(
      "df must contain these columns: ",
      paste(required_cols, collapse = ", ")
    )
  }

  if (!inherits(df$Date, "Date")) {
    stop("df$Date must be of class Date.")
  }

  if (!is.numeric(df$Storage)) {
    df$Storage <- suppressWarnings(as.numeric(df$Storage))
  }

  if (all(is.na(df$Storage))) {
    stop("df$Storage contains no valid numeric values.")
  }

  ## ---- Validate scalar parameters ----
  scalar_parameters <- list(
    Smin = Smin,
    Smax = Smax,
    Qmin = Qmin,
    Qmax = Qmax,
    logistic_k = logistic_k,
    logistic_midpoint = logistic_midpoint,
    missing_weight = missing_weight
  )

  for (parameter_name in names(scalar_parameters)) {
    parameter_value <- scalar_parameters[[parameter_name]]

    if (!is.numeric(parameter_value) ||
        length(parameter_value) != 1 ||
        is.na(parameter_value) ||
        !is.finite(parameter_value)) {
      stop(parameter_name, " must be one finite numeric value.")
    }
  }

  if (Smin >= Smax) {
    stop("Smin must be less than Smax.")
  }

  if (Qmin > Qmax) {
    stop("Qmin must be less than or equal to Qmax.")
  }

  if (Qmin < 0 || Qmax < 0) {
    stop("Qmin and Qmax cannot be negative.")
  }

  if (logistic_k <= 0) {
    stop("logistic_k must be greater than zero.")
  }

  if (logistic_midpoint < 0 || logistic_midpoint > 1) {
    stop("logistic_midpoint must be between 0 and 1.")
  }

  ## ---- Validate logical parameters ----
  logical_parameters <- list(
    normalize_weights = normalize_weights,
    cap_release = cap_release,
    plot = plot
  )

  for (parameter_name in names(logical_parameters)) {
    parameter_value <- logical_parameters[[parameter_name]]

    if (!is.logical(parameter_value) ||
        length(parameter_value) != 1 ||
        is.na(parameter_value)) {
      stop(parameter_name, " must be TRUE or FALSE.")
    }
  }

  ## ---- Validate seasonal weights ----
  if (!is.numeric(seasonal_weights) ||
      length(seasonal_weights) != 12) {
    stop(
      "seasonal_weights must be a numeric vector containing ",
      "12 monthly values."
    )
  }

  if (is.null(names(seasonal_weights))) {
    stop(
      "seasonal_weights must be named using month.abb: ",
      paste(month.abb, collapse = ", ")
    )
  }

  if (!all(month.abb %in% names(seasonal_weights))) {
    stop(
      "seasonal_weights must contain names for all months: ",
      paste(month.abb, collapse = ", ")
    )
  }

  # Reorder weights explicitly as January through December
  seasonal_weights <- seasonal_weights[month.abb]

  if (any(!is.finite(seasonal_weights))) {
    stop("seasonal_weights must contain only finite numeric values.")
  }

  if (any(seasonal_weights < 0)) {
    stop("seasonal_weights cannot contain negative values.")
  }

  if (normalize_weights) {
    weight_mean <- mean(seasonal_weights)

    if (!is.finite(weight_mean) || weight_mean <= 0) {
      stop(
        "The mean of seasonal_weights must be greater than zero."
      )
    }

    seasonal_weights <- seasonal_weights / weight_mean
  }

  ## ---- Add month information ----
  out <- df
  out$Month <- format(out$Date, "%b")

  ## ---- Normalize storage between zero and one ----
  storage_index <- (
    out$Storage - Smin
  ) / (Smax - Smin)

  storage_index <- pmin(
    1,
    pmax(0, storage_index)
  )

  ## ---- Calculate release fraction ----
  if (rule == "linear") {
    release_fraction <- storage_index
  } else {
    release_fraction <- 1 / (
      1 + exp(
        -logistic_k *
          (storage_index - logistic_midpoint)
      )
    )
  }

  ## ---- Apply seasonal weights ----
  weights_used <- as.numeric(
    seasonal_weights[out$Month]
  )

  missing_weights <- is.na(weights_used)

  if (any(missing_weights)) {
    weights_used[missing_weights] <- missing_weight
  }

  ## ---- Calculate release ----
  base_release <- Qmin +
    release_fraction * (Qmax - Qmin)

  release <- base_release * weights_used

  ## ---- Optionally constrain release to Qmin-Qmax ----
  if (cap_release) {
    release <- pmin(
      Qmax,
      pmax(Qmin, release)
    )
  }

  ## ---- Build output ----
  out$Storage_Index <- storage_index
  out$Seasonal_Weight <- weights_used
  out$Release_Fraction <- release_fraction
  out$Release <- release

  ## ---- Optional plot ----
  if (plot) {
    if (requireNamespace("ggplot2", quietly = TRUE)) {
      release_plot <- ggplot2::ggplot(
        out,
        ggplot2::aes(
          x = Date,
          y = Release
        )
      ) +
        ggplot2::geom_line(
          color = "steelblue",
          linewidth = 1
        ) +
        ggplot2::theme_minimal() +
        ggplot2::labs(
          title = "Daily Reservoir Release Policy",
          subtitle = paste(
            "Rule:",
            rule,
            "| Seasonal weights normalized:",
            normalize_weights
          ),
          x = "Date",
          y = "Release (m3/s)"
        )

      print(release_plot)
    } else {
      warning(
        "Install ggplot2 to generate the release plot.",
        call. = FALSE
      )
    }
  }

  ## ---- Store model information as attributes ----
  attr(out, "weights_used") <- seasonal_weights
  attr(out, "mapping_rule") <- rule
  attr(out, "Smin") <- Smin
  attr(out, "Smax") <- Smax
  attr(out, "Qmin") <- Qmin
  attr(out, "Qmax") <- Qmax
  attr(out, "logistic_k") <- logistic_k
  attr(out, "logistic_midpoint") <- logistic_midpoint

  out
}
